name: NoRegenNoHunger
version: '1.0'
main: com.timedust.noRegenNoHunger.NoRegenNoHunger
api-version: '1.16'

commands:
  noregennohunger:
    description: "Reload plugin config"
  createworld:
    description: "Creating test world"

permissions:
  noregennohunger.reload:
    description: "Allows reloading the plugin config"
    default: op
